package cn.zhuangcloud.karori.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseKofuku<M extends BaseKofuku<M>> extends Model<M> implements IBean {

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setQ1(java.lang.Integer q1) {
		set("q1", q1);
	}
	
	public java.lang.Integer getQ1() {
		return getInt("q1");
	}

	public void setQ2(java.lang.Integer q2) {
		set("q2", q2);
	}
	
	public java.lang.Integer getQ2() {
		return getInt("q2");
	}

	public void setQ3(java.lang.Integer q3) {
		set("q3", q3);
	}
	
	public java.lang.Integer getQ3() {
		return getInt("q3");
	}

	public void setQ4(java.lang.Integer q4) {
		set("q4", q4);
	}
	
	public java.lang.Integer getQ4() {
		return getInt("q4");
	}

	public void setQ5(java.lang.Integer q5) {
		set("q5", q5);
	}
	
	public java.lang.Integer getQ5() {
		return getInt("q5");
	}

}
