package cn.zhuangcloud.karori.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseComposition<M extends BaseComposition<M>> extends Model<M> implements IBean {

	public java.lang.Integer getCid() {
		return getInt("cid");
	}

	public void setCid(java.lang.Integer cid) {
		set("cid", cid);
	}

	/**
	 * kcal
	 */
	public java.lang.Integer getCalorie() {
		return getInt("calorie");
	}

	/**
	 * kcal
	 */
	public void setCalorie(java.lang.Integer calorie) {
		set("calorie", calorie);
	}

	/**
	 * g
	 */
	public java.lang.Integer getProtein() {
		return getInt("protein");
	}

	/**
	 * g
	 */
	public void setProtein(java.lang.Integer protein) {
		set("protein", protein);
	}

	/**
	 * g
	 */
	public java.lang.Integer getFat() {
		return getInt("fat");
	}

	/**
	 * g
	 */
	public void setFat(java.lang.Integer fat) {
		set("fat", fat);
	}

	/**
	 * g
	 */
	public java.lang.Integer getCarbohydrate() {
		return getInt("carbohydrate");
	}

	/**
	 * g
	 */
	public void setCarbohydrate(java.lang.Integer carbohydrate) {
		set("carbohydrate", carbohydrate);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getSodium() {
		return getInt("sodium");
	}

	/**
	 * mg
	 */
	public void setSodium(java.lang.Integer sodium) {
		set("sodium", sodium);
	}

	/**
	 * g
	 */
	public java.lang.Integer getSalt() {
		return getInt("salt");
	}

	/**
	 * g
	 */
	public void setSalt(java.lang.Integer salt) {
		set("salt", salt);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getCholesterol() {
		return getInt("cholesterol");
	}

	/**
	 * mg
	 */
	public void setCholesterol(java.lang.Integer cholesterol) {
		set("cholesterol", cholesterol);
	}

	/**
	 * g
	 */
	public java.lang.Integer getSugar() {
		return getInt("sugar");
	}

	/**
	 * g
	 */
	public void setSugar(java.lang.Integer sugar) {
		set("sugar", sugar);
	}

	/**
	 * ug
	 */
	public java.lang.Integer getVitaminA() {
		return getInt("vitaminA");
	}

	/**
	 * ug
	 */
	public void setVitaminA(java.lang.Integer vitaminA) {
		set("vitaminA", vitaminA);
	}

	/**
	 * ug
	 */
	public java.lang.Integer getVitaminD() {
		return getInt("vitaminD");
	}

	/**
	 * ug
	 */
	public void setVitaminD(java.lang.Integer vitaminD) {
		set("vitaminD", vitaminD);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getVitaminE() {
		return getInt("vitaminE");
	}

	/**
	 * mg
	 */
	public void setVitaminE(java.lang.Integer vitaminE) {
		set("vitaminE", vitaminE);
	}

	/**
	 * ug
	 */
	public java.lang.Integer getVitaminK() {
		return getInt("vitaminK");
	}

	/**
	 * ug
	 */
	public void setVitaminK(java.lang.Integer vitaminK) {
		set("vitaminK", vitaminK);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getVitaminB1() {
		return getInt("vitaminB1");
	}

	/**
	 * mg
	 */
	public void setVitaminB1(java.lang.Integer vitaminB1) {
		set("vitaminB1", vitaminB1);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getVitaminB2() {
		return getInt("vitaminB2");
	}

	/**
	 * mg
	 */
	public void setVitaminB2(java.lang.Integer vitaminB2) {
		set("vitaminB2", vitaminB2);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getVitaminB6() {
		return getInt("vitaminB6");
	}

	/**
	 * mg
	 */
	public void setVitaminB6(java.lang.Integer vitaminB6) {
		set("vitaminB6", vitaminB6);
	}

	/**
	 * ug
	 */
	public java.lang.Integer getVitaminB12() {
		return getInt("vitaminB12");
	}

	/**
	 * ug
	 */
	public void setVitaminB12(java.lang.Integer vitaminB12) {
		set("vitaminB12", vitaminB12);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getVitaminC() {
		return getInt("vitaminC");
	}

	/**
	 * mg
	 */
	public void setVitaminC(java.lang.Integer vitaminC) {
		set("vitaminC", vitaminC);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getCalcium() {
		return getInt("calcium");
	}

	/**
	 * mg
	 */
	public void setCalcium(java.lang.Integer calcium) {
		set("calcium", calcium);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getIron() {
		return getInt("iron");
	}

	/**
	 * mg
	 */
	public void setIron(java.lang.Integer iron) {
		set("iron", iron);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getMagnesium() {
		return getInt("magnesium");
	}

	/**
	 * mg
	 */
	public void setMagnesium(java.lang.Integer magnesium) {
		set("magnesium", magnesium);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getZinc() {
		return getInt("zinc");
	}

	/**
	 * mg
	 */
	public void setZinc(java.lang.Integer zinc) {
		set("zinc", zinc);
	}

	/**
	 * mg
	 */
	public java.lang.Integer getPotassium() {
		return getInt("potassium");
	}

	/**
	 * mg
	 */
	public void setPotassium(java.lang.Integer potassium) {
		set("potassium", potassium);
	}

}
