package cn.zhuangcloud.karori.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTarget<M extends BaseTarget<M>> extends Model<M> implements IBean {

	public void setTid(java.lang.Integer tid) {
		set("tid", tid);
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public void setUid(java.lang.Integer uid) {
		set("uid", uid);
	}
	
	public java.lang.Integer getUid() {
		return getInt("uid");
	}

	public void setTargetCalorie(java.lang.Integer targetCalorie) {
		set("target_calorie", targetCalorie);
	}
	
	public java.lang.Integer getTargetCalorie() {
		return getInt("target_calorie");
	}

	public void setTargetProtein(java.lang.Integer targetProtein) {
		set("target_protein", targetProtein);
	}
	
	public java.lang.Integer getTargetProtein() {
		return getInt("target_protein");
	}

	public void setTargetFat(java.lang.Integer targetFat) {
		set("target_fat", targetFat);
	}
	
	public java.lang.Integer getTargetFat() {
		return getInt("target_fat");
	}

	public void setTargetCarbohydrate(java.lang.Integer targetCarbohydrate) {
		set("target_carbohydrate", targetCarbohydrate);
	}
	
	public java.lang.Integer getTargetCarbohydrate() {
		return getInt("target_carbohydrate");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
