package cn.zhuangcloud.karori.common.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseShortUrl<M extends BaseShortUrl<M>> extends Model<M> implements IBean {

	public void setSuid(java.lang.Integer suid) {
		set("suid", suid);
	}
	
	public java.lang.Integer getSuid() {
		return getInt("suid");
	}

	public void setShortUrl(java.lang.String shortUrl) {
		set("short_url", shortUrl);
	}
	
	public java.lang.String getShortUrl() {
		return getStr("short_url");
	}

	public void setLongUrl(java.lang.String longUrl) {
		set("long_url", longUrl);
	}
	
	public java.lang.String getLongUrl() {
		return getStr("long_url");
	}

	/**
	 * uid
	 */
	public void setCreator(java.lang.Integer creator) {
		set("creator", creator);
	}
	
	/**
	 * uid
	 */
	public java.lang.Integer getCreator() {
		return getInt("creator");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
