package cn.zhuangcloud.karori.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("fjsr_kofuku", "uid", Kofuku.class);
		arp.addMapping("t_composition", "cid", Composition.class);
		arp.addMapping("t_food", "fid", Food.class);
		arp.addMapping("t_log", "lid", Log.class);
		arp.addMapping("t_share", "sid", Share.class);
		arp.addMapping("t_short_url", "suid", ShortUrl.class);
		arp.addMapping("t_target", "tid", Target.class);
		arp.addMapping("t_user", "uid", User.class);
	}
}

