package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseComposition;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Composition extends BaseComposition<Composition> {

}
