package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseComposition;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Composition extends BaseComposition<Composition> {

    public void calculate(Double unit) throws NoSuchMethodException, InvocationTargetException, IllegalAccessException {
        Composition bean = this;

        Method[] methods = this.getClass().getMethods();
        for (Method method : methods) {
            String methodName = method.getName();
            if (!methodName.startsWith("set") || methodName.length() <= 3) {    // only setter method
                continue;
            }
            Class<?>[] types = method.getParameterTypes();
            if (types.length != 1) {                        // only one parameter
                continue;
            }
            String attrName = methodName.substring(3);
            if (attrName.equals("Cid") || attrName.equals("Uuid"))
                continue;
            Method getter = bean.getClass().getMethod("get" + attrName);
            Double value = (Double) getter.invoke(bean);
            if (null == value)
                continue;
            method.invoke(bean, value * 100 / unit);
        }
    }


}
