package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseFood;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Food extends BaseFood<Food> {

}
