package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseKofuku;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Kofuku extends BaseKofuku<Kofuku> {
	
}
