package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {

}
