package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseShare;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Share extends BaseShare<Share> {
	
}
