package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseShortUrl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ShortUrl extends BaseShortUrl<ShortUrl> {
	
}
