package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseTarget;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Target extends BaseTarget<Target> {
	
}
