package cn.zhuangcloud.karori.common.model;

import cn.zhuangcloud.karori.common.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {

}
